name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          tools: composer

      - name: Install Composer deps
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Lint (PHPCS)
        run: composer run lint

      - name: Static analysis (PHPStan)
        run: composer run stan

      - name: Unit tests (PHPUnit)
        run: composer run test

  e2e:
    needs: php
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Node deps
        run: npm ci

      - name: Run E2E (wp-env + Playwright)
        run: npm run e2e:ci
      - name: wp-env logs (always)
        if: always()
        run: npx wp-env logs --all > wp-env.log || true

      - name: Upload wp-env logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wp-env-logs
          path: wp-env.log
          if-no-files-found: ignore

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload Playwright JUnit XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-junit
          path: test-results/*.xml
          if-no-files-found: ignore
