name: E2E - Playwright

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci || npm install
      - name: Install Playwright
        run: npm run e2e:install
      - name: Run E2E tests
        env:
          E2E_BASE_URL: ${{ secrets.E2E_BASE_URL }}
        run: npm run e2e
