name: E2E - Playwright (wp-env)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci || npm install

      - name: Install Playwright browsers
        run: npm run e2e:install

      - name: Start WordPress (wp-env)
        run: npx wp-env start

      - name: Wait for WP to be ready
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:8888 > /dev/null; then
              echo "WordPress is up ✨"
              exit 0
            fi
            echo "Waiting for WordPress... ($i/60)"
            sleep 5
          done
          echo "WordPress did not start in time" >&2
          exit 1

      - name: Run E2E tests
        env:
          E2E_BASE_URL: http://localhost:8888
        run: npm run e2e

      - name: wp-env logs (always)
        if: always()
        run: npx wp-env logs --all || true

      - name: Stop WordPress (always)
        if: always()
        run: npx wp-env stop
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload JUnit XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-junit
          path: test-results/junit.xml
          if-no-files-found: ignore
          retention-days: 7
